### PR TITLE
Updating to UFR format

### LINKED ISSUE #18: No AxisValue in STAT table
`gftools gen-stat` can solve the problem.

See google/fonts#2391

### PR DESCRIPTION
**Pull request by aaronbell**
I'm helping update repositories to Google's [United Font Repro](https://github.com/googlefonts/Unified-Font-Repository) format, as well as correcting STAT table issues in variable fonts. As an added benefit to this process, the font will now build automatically when PRs are accepted. 

Closes #18

Once merged in, we'll submit an update to Google Fonts. Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by m4rc1e** [comment]
ping @NDISCOVER

**Comment by NDISCOVER** [comment]
@m4rc1e @aaronbell I am having conflicts merging. Conflicting file: requirements txt.

**Comment by aaronbell** [comment]
You can just use the new version of the file and clear the old code out. 

Thanks!

```
fontmake>=2.4
fontbakery>=0.7
gftools>=0.7
```

**Comment by RosaWagner** [comment]
@NDISCOVER can you copy paste these 3 lines in the requirements.txt to resolve the conflict and merge the PR? 
the fix is gonna go to production and we would like to keep all versions in sync.

fontmake>=2.4
fontbakery>=0.7
gftools>=0.7

**Comment by aaronbell** [comment]
Interestingly, it looks like I could resolve it. @NDISCOVER, you should be able to merge easy now.

**Pull request merged**
